### ISSUE TITLE
Fix numbered pagination Bug on Custom Post

### ISSUE THREAD

**Issue by BerkasKita** [BerkasKita/Korenime#1]
# Preview
<img alt=""  src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi6t18gM5axCw0-ZK1VkenbWV6K-teUxZJQ3X2NdeyVTIcnzy-fzNA8lxTOz0bJBiDlHHqL8PNFoMo3nJWuniUtNlyA1v2mvBWlPtl4LtuKaPmBXEXSYVKzjcvZwglx8n4zdG1L40MTK6BCexoouVMUuIK7dWgARVaE4AEcQPIN49vEq_SKLSMlyQI0PNVw/s0/jshfkhihurfrfohirfoiwrfhoirfohewrfihoerfuhoerferf.jpg" loading="lazy">

# Steps
+ Go to `Thema`
+ Go to `Edit HTML`
+ Find `#pagination {...}`  for the code that looks something like this:

  ```css
  #pagination{overflow:hidden;text-align:center;margin:10px 0;line-height:30px;font-size:15px}
  ```
+ Change `line-height:30px;` to `line-height:15px;`

  ```css
  #pagination{overflow:hidden;text-align:center;margin:10px 0;line-height:15px;font-size:15px}
  ```
